version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/app/test.db:/app/app/test.db 
      - ./backend/requirements.txt:/app/requirements.txt
      - backend_data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///app/app/test.db  # Ruta correcta del archivo test.db dentro del contenedor
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  backend_data:

networks:
  app-network:
    driver: bridge
